server:
  servlet:
    context-path: /api
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:incidents
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode:
      platform: h2
      schema-locations: classpath:db/init/schema.sql
      data-locations: classpath:db/init/data.sql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: WARN
    com.hsbc.incident: DEBUG
